default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: db

development:
  <<: *default
  database: location_app_development

test:
  <<: *default
  database: location_app_test

production:
  <<: *default
  database: location_app_production
  username: app
  password: <%= ENV["APP_DATABASE_PASSWORD"] %>
